name: publish-to-registry

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: number
        default: 18
      npm-registry:
        required: false
        type: string
        default: https://registry.npmjs.org/
      npmrc:
        required: false
        type: string
        default: .npmrc
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node-version}}
          registry-url: ${{inputs.npm-registry}}
      - run: npm i && npm run build
      - run: npm publish --userconfig ${{inputs.npmrc}} --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.token}}
